name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: Run all tests
      run: make test
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy
